title: Retro Dev Blog
description: A retro-styled developer blog with an 80s aesthetic
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
